source 'https://rubygems.org'
gemspec

gem 'floq', path: '../floq'

gem 'better_errors'
gem 'binding_of_caller'

gem 'rack-livereload'

gem 'guard'
gem 'guard-shell'
gem 'guard-bundler'
gem 'guard-livereload'
